### ISSUE TITLE
Sonoff S20 -  Tasmota error

### ISSUE THREAD

**Issue by elRadix** [danmed/Home-Assistant---Sonoff-Component#1]
Issue still not fixed with the latest update

```
2017-11-29 21:09:56 ERROR (SyncWorker_7) [custom_components.switch.sonoff_tasmota] Switching failed
2017-11-29 21:09:56 ERROR (MainThread) [homeassistant.helpers.entity] Update for switch.kodi_tv fails
Traceback (most recent call last):
  File "/srv/homeassistant/lib/python3.6/site-packages/homeassistant/helpers/entity.py", line 199, in async_update_ha_state
    yield from self.async_device_update()
  File "/srv/homeassistant/lib/python3.6/site-packages/homeassistant/helpers/entity.py", line 306, in async_device_update
    yield from self.hass.async_add_job(self.update)
  File "/usr/local/lib/python3.6/asyncio/futures.py", line 331, in __iter__
    yield self  # This tells Task to wait for completion.
  File "/usr/local/lib/python3.6/asyncio/tasks.py", line 244, in _wakeup
    future.result()
  File "/usr/local/lib/python3.6/asyncio/futures.py", line 244, in result
    raise self._exception
  File "/usr/local/lib/python3.6/concurrent/futures/thread.py", line 55, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/homeassistant/.homeassistant/custom_components/switch/sonoff_tasmota.py", line 102, in update
    self._state = self._query_state()
  File "/home/homeassistant/.homeassistant/custom_components/switch/sonoff_tasmota.py", line 81, in _query_state
    return req.json()['state'] == 'On'
  File "/srv/homeassistant/lib/python3.6/site-packages/requests/models.py", line 892, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/local/lib/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/lib/python3.6/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

**Comment by danmed** [comment]
I'm going to have to flash a plug to tasmota to test this out so it may have to wait until the weekend.

Thanks for testing though.

**Comment by elRadix** [comment]
sure no problem

**Comment by elRadix** [comment]
did you have a chance to fix the script in the meantime?
